/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/coffee-baked.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.coffee.geometry}
        material={materials.palette}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        position={[0, -1, 0]}
      />
    </group>
  );
}

useGLTF.preload('/coffee-baked.glb');
